;;;
;;; PgBouncer configuration file
;;;

;; database name = connect string
;;
;; connect string params:
;;   dbname= host= port= user= password= auth_user=
;;   client_encoding= datestyle= timezone=
;;   pool_size= reserve_pool= max_db_connections=
;;   pool_mode= connect_query= application_name=

[databases]
agai_local = host=postgres port=5432 dbname=agai_local

[pgbouncer]
;logfile = /var/log/postgresql/pgbouncer.log
;pidfile = /var/run/postgresql/pgbouncer.pid
listen_addr = *
;listen_addr = 192.168.252.5
listen_port = 6432
;listen_port = 5432
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt
admin_users = agai_local
stats_users = agai_local
pool_mode = session
server_reset_query = DISCARD ALL
ignore_startup_parameters = extra_float_digits

;server_check_query = select 1
;server_check_delay = 60

;; Close servers in session pooling mode after a RECONNECT, RELOAD,
;; etc. when they are idle instead of at the end of the session.
;server_fast_close = 0

max_client_conn = 2000
default_pool_size = 40

;admin_users = pgb_admin

;; Minimum number of server connections to keep in pool.
;min_pool_size = 0

; how many additional connection to allow in case of trouble
reserve_pool_size = 20

;; If a clients needs to wait more than this many seconds, use reserve
;; pool.
;reserve_pool_timeout = 15

;; How many total connections to a single database to allow from all
;; pools
;max_db_connections = 0
;max_user_connections = 0
